# (remove any top‑level `version:` line – Compose V2 ignores it)
services:
  # ── 1) initialize Airflow metadata DB ────────────────────────────────────
  airflow-init:
    image: apache/airflow:3.0.0
    command: >
      bash -c "airflow db upgrade &&
               airflow users create \
                 --username admin --firstname Admin --lastname User \
                 --role Admin --email admin@example.com"

  # ── 2) Airflow webserver ─────────────────────────────────────────────────
  airflow-webserver:
    image: apache/airflow:3.0.0
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 3

  # ── 3) Airflow scheduler ─────────────────────────────────────────────────
  airflow-scheduler:
    image: apache/airflow:3.0.0
    depends_on:
      - airflow-webserver

  # ── 4) Your Flask backend/API ───────────────────────────────────────────
  backend:
    build: .
    volumes:
      - ./app/datasets:/app/datasets   # data available at runtime, not baked in
    ports:
      - "5000:5000"
    depends_on:
      - airflow-webserver

  # ── 5) Your React frontend/UI ──────────────────────────────────────────
  frontend:
    image: node:16
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm","start"]
    ports:
      - "8000:8000"
    depends_on:
      - backend
